# Generated by Django 5.2.5 on 2026-04-04 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='community_gallery/')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='communities.community')),
            ],
        ),
    ]
