# Generated by Django 6.0.5 on 2026-05-10 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0003_calendarevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                related_name="managed_communities_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
