# Generated by Django 6.0.5 on 2026-05-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0005_populate_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="community",
            name="manager",
        ),
    ]
