# Generated by Django 6.0.5 on 2026-05-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0006_remove_manager_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="join_code",
            field=models.CharField(
                blank=True,
                help_text="A unique code for users to join the community",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
