# Generated by Django 6.0.5 on 2026-05-11 08:46

from django.db import migrations


import random
import string

def generate_join_code():
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))

def populate_join_codes(apps, schema_editor):
    Community = apps.get_model('communities', 'Community')
    for community in Community.objects.all():
        if not community.join_code:
            code = generate_join_code()
            while Community.objects.filter(join_code=code).exists():
                code = generate_join_code()
            community.join_code = code
            community.save()

class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0007_community_join_code"),
    ]

    operations = [
        migrations.RunPython(populate_join_codes, reverse_code=migrations.RunPython.noop),
    ]
