# Generated by Django 6.0.5 on 2026-05-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0008_populate_join_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="vdot_group_a",
            field=models.FloatField(
                blank=True, help_text="Default VDOT for Group A", null=True
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="vdot_group_b",
            field=models.FloatField(
                blank=True, help_text="Default VDOT for Group B", null=True
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="vdot_group_c",
            field=models.FloatField(
                blank=True, help_text="Default VDOT for Group C", null=True
            ),
        ),
    ]
