# Generated by Django 6.0.5 on 2026-05-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0009_community_vdot_group_a_community_vdot_group_b_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="track_api_link",
            field=models.URLField(
                blank=True,
                help_text="OpenActive API feed URL for track schedule",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="track_location_keyword",
            field=models.CharField(
                blank=True,
                help_text="Keyword to identify the track in the API (e.g., 'Mile End Track')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="track_training_day",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                help_text="Day of the week the community trains at the track",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="track_training_time",
            field=models.TimeField(
                blank=True,
                help_text="Time of the training session (local time)",
                null=True,
            ),
        ),
    ]
