# Generated by Django 6.1 on 2026-08-15 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_community_vdot_group_a_community_vdot_group_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='num_groups',
            field=models.PositiveSmallIntegerField(default=3, help_text='Number of training groups (1–9). Defaults to 3.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
