# Generated by Django 6.1 on 2026-08-15 10:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0010_community_num_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityGroupVDOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('display_name', models.CharField(default='', max_length=50)),
                ('default_vdot', models.FloatField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_vdots', to='communities.community')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('community', 'position'), name='communitygroupvdot_unique_position_per_community')],
            },
        ),
    ]
