# Generated by Django 6.1 on 2026-08-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0012_backfill_group_vdots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='vdot_group_a',
        ),
        migrations.RemoveField(
            model_name='community',
            name='vdot_group_b',
        ),
        migrations.RemoveField(
            model_name='community',
            name='vdot_group_c',
        ),
    ]
