# Generated by Django 5.2.5 on 2026-04-04 17:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_remove_order_total_price_order_base_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='merchitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MerchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='merch_images/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='merch.merchitem')),
            ],
        ),
    ]
