# Generated by Django 5.2.5 on 2026-04-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0003_remove_merchitem_image_url_merchitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchitem',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
