# Generated by Django 5.2.5 on 2026-04-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0004_merchitem_is_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_INVOICE', 'Pending Invoice Calculation'), ('DRAFT_GENERATED', 'Draft Invoice Generated'), ('PAID_AWAITING_PRINT', 'Paid - Awaiting Print'), ('PAYMENT_FAILED', 'Payment Failed')], default='PENDING_INVOICE', max_length=50),
        ),
    ]
