# Generated by Django 6.0.5 on 2026-05-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merch", "0005_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_INVOICE", "Pending Invoice Calculation"),
                    ("DRAFT_GENERATED", "Draft Invoice Generated"),
                    ("PAID_AWAITING_PRINT", "Paid - Awaiting Print"),
                    ("SENT_TO_MANUFACTURER", "Sent to Manufacturer"),
                    ("RECEIVED_FROM_MANUFACTURER", "Received from Manufacturer"),
                    ("DELIVERED", "Delivered"),
                    ("PAYMENT_FAILED", "Payment Failed"),
                ],
                default="PENDING_INVOICE",
                max_length=50,
            ),
        ),
    ]
