# Generated by Django 5.2.5 on 2026-04-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='sessiongroup',
            name='structure_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
