# Generated by Django 5.2.5 on 2026-04-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_planner', '0004_trainingblock_blocksessiontemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocksessiontemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
