# Generated by Django 6.0.5 on 2026-05-11 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0006_remove_manager_field"),
        ("session_planner", "0005_blocksessiontemplate_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingblock",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_blocks",
                to="communities.community",
            ),
        ),
        migrations.AddField(
            model_name="trainingblock",
            name="is_tradeable",
            field=models.BooleanField(default=False),
        ),
    ]
